nodejs/postject

.circleci/config.yml
With this change, it would be possible to use Postject without building
it from source.
=> Upload artifacts

.circleci/config.yml, build/deps.mk, build/system.mk
Couple of rough edges in this PR but just trying to unblock:
* GitHub is showing the Windows job name as `default` instead of `build-win/default`
* Tests aren't run on Windows currently
=> ci: add executors for macOS and Windows

README.markdown
The step for installation dependencies was missing.
=> [skip ci] docs: fix building steps for linux

.circleci/config.yml, build/deps.mk
The only Linux distributions we were building and testing on are alpine and debian. This change also adds the linux executor which was unused.
=> ci: build and test on linux on CI

.github/workflows/semantic-commits.yml
We've been using semantic commit messages for this project, let's enforce it.
=> chore: add semantic commit check

.gitattributes
We should avoid making changes to the global git config if we can help it. This change stops setting the value for `core.autocrlf` globally on CI by moving it to the `.gitattributes` file which is local to a git repository.
This should help out with removing this change from
https://github.com/postmanlabs/postject/pull/8/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R68-R69.
Refs: https://stackoverflow.com/a/52996849
=> chore: enforce `linefeeds` at `eol`s in the `.gitattributes` file [skip ci]

README.markdown
Now that there's a published package let's add the badge.
=> chore: add npm release badge to README

.npmignore
This excludes the files that we don't want to publish to the npm package.
=> chore: add `.npmignore` file

README.markdown
The "Building" section has a lower priority.
=> docs: move the "Usage" section after the "Install" section

package-lock.json, package.json
I think this was the intended version. (reasons discussed in DMs)
=> chore: use `alpha` instead of `dev` in package version

.npmignore
I think having `postject-api.h` in the `.npmignore` file caused the copied file inside `dist/` to get excluded from the package built with `npm pack`. Explicitly including it fixes the problem.
=> fix: exclude `dist/postject-api.h` from `.npmignore`

.npmignore
This is what the package would look like after this change:
```sh
$ tar -xvf postject-1.0.0-alpha.1.tgz
$ tree -a package
package
├── LICENSE
├── README.markdown
├── dist
│   ├── main.js
│   ├── postject-api.h
│   ├── postject.js
│   └── postject.wasm
└── package.json
```
I did `tree` without the `-a` and that's why I missed the `.` files initially. :)
=> chore: remove `.gitattributes` and `.github/` from `.npmignore`

CMakeLists.txt, test/cli.mjs
After building Postject with `-sASSERTIONS` enabled, the error looked like this:
```
Aborted(Cannot enlarge memory arrays to size 82239488 bytes (OOM). Either (1) compile with -sINITIAL_MEMORY=X with X higher than the current value 16777216, (2) compile with -sALLOW_MEMORY_GROWTH which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with -sABORTING_MALLOC=0)
```
so I followed option 2 in this change.
Fixes: https://github.com/postmanlabs/postject/issues/42
=> fix: OOM abort error while injecting data

.github/workflows/semantic-commits.yml
Just a bit more security tightening to limit permissions on the workflow.
=> ci: tighten permissions on GitHub workflow

scripts/build.mjs, test/cli.mjs
Fixes: https://github.com/postmanlabs/postject/issues/50
=> fix: get rid of undefined symbols from the bundled api

CODE_OF_CONDUCT.md, CONTRIBUTING.md
This change adds a `CODE_OF_CONDUCT.md` file and a `CONTRIBUTING.md` file to the project. This is a requirement for transferring as documented in: https://github.com/nodejs/admin/blob/a99c444662467d596753affb2ce192250f4f4b6c/transfer-repo-into-the-org.md#step-1-get-the-repository-ready.
Refs: https://github.com/nodejs/admin/issues/739
=> docs: make postject ready for transferring to the nodejs org

test/cli.mjs
=> test: add test for code signing on macOS

postject-api.h
No need for it.
Refs: https://github.com/nodejs/node/pull/45038#discussion_r1005654541
=> chore: remove Postman copyright from `postject-api.h`

postject-api.h
Fixes: https://github.com/nodejs/postject/issues/68
=> fix: compilation error on macOS >= 13

README.markdown, postject-api.h, src/api.js, src/cli.js, test/cli.mjs, test/test.c, test/test.cpp
Fixes: https://github.com/postmanlabs/postject/issues/58
=> feat: add a fuse to speed up the case where no resource is present

package.json
This commit replaces the package.json references
to postmanlabs with nodejs to reflect reality and
because the npm page displays these.
=> chore: remove postmanlabs references in package.json

postject-api.h, test/test.c
The program headers base address values returned by `getauxval(AT_PHDR)` and `dl_iterate_phdr()` are identical only on
`g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0`. However, the values are totally different on `clang version 10.0.0-4ubuntu1` and `g++ (GCC) 8.5.0 20210514 (Red Hat 8.5.0-16)`.
Since the `dl_iterate_phdr()` approach seems to work for all the 3 compilers, I think we should proceed with that.
Turns out, this happens because PIE is not enabled by default on the compilers which produce binaries that are crashing.
Fixes: https://github.com/nodejs/postject/issues/70
Refs: https://github.com/nodejs/postject/issues/76 (actually `Fixes: ` but I'll add `Fixes: ` on the postject version upgrade PR in Node.js)
(Node.js PR to test this - https://github.com/nodejs/node/pull/46868)
=> fix: crash in `postject_find_resource()` on Linux

patches/lief/0001-feat-add-log-level-with-l.patch, src/cli.js, test/cli.mjs, vendor/lief/src/logging.cpp, vendor/lief/src/logging.hpp
=> feat: add base logger

test/cli.mjs
Originated in https://github.com/nodejs/postject/pull/73. (fixed with `npm run format`)
=> fix: formatting in test/cli.mjs

test/cli.mjs
https://github.com/nodejs/postject/pull/73 uncommented an assertion which is known to fail on linux, so comment it once again.
=> test: fix test on linux

.npmignore
There's no reason to make https://github.com/nodejs/postject/tree/main/patches/ a part of the release.
=> chore: add `patches/` to `.npmignore`

src/postject.cpp, test/cli.mjs
This change replaces the [`vecFromJSArray()`](https://emscripten.org/docs/api_reference/val.h.html?highlight=vecfromjsarray#_CPPv4N10emscripten10emscripten3val14vecFromJSArrayERK3val) call in `vec_from_val()` with a call to [`convertJSArrayToNumberVector()`](https://emscripten.org/docs/api_reference/val.h.html?highlight=convertjsarraytonumbervector#_CPPv4N10emscripten10emscripten3val28convertJSArrayToNumberVectorERK3val), which reduces the time consumption of Postject from ~30s to ~6s on a Mach-O Node.js binary when run on my x86_64 macOS.
Fixes: https://github.com/nodejs/postject/issues/85
Refs: https://github.com/emscripten-core/emscripten/pull/11119
CI: https://app.circleci.com/pipelines/github/RaisinTen/postject/8/workflows/6ac6bd04-5249-4c36-8daa-f86e8a52d7db
=> feat: make postject faster
